### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/progress#3]
* [x] initial version (#2)
* [x] add a pubsub (#5)
* [x] `step.SetAsCurrent()` (#7)
* [x] `prog.GetPercent()` (#7)
* [x] `step.SetProgress(float64)` (#8)
* [x] support the "pause"/"stopped" state when nothing is running, but when the progress is not finished (#38)
* [ ] support nested progress or at least a per-step progress
* [ ] support manual and automatic completion estimate
* [ ] support always-growing progress based on manual estimate
* [ ] support weights to make a step more important than another
* [ ] 100% test coverage
* [ ] refactor locking to allocate smaller channels
* [ ] `progress.NewNop()`
